"""update_some_schema

Revision ID: cab4801612b8
Revises: 307df4c692f6
Create Date: 2026-08-13 16:32:18.869044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cab4801612b8'
down_revision: Union[str, Sequence[str], None] = '307df4c692f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateurs', sa.Column('departement_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'utilisateurs', 'departements', ['departement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'utilisateurs', type_='foreignkey')
    op.drop_column('utilisateurs', 'departement_id')
    # ### end Alembic commands ###
