"""update_some_schema_4

Revision ID: fe0315779649
Revises: a08bb63bf261
Create Date: 2026-08-13 16:48:50.795548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0315779649'
down_revision: Union[str, Sequence[str], None] = 'a08bb63bf261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('utilisateurs', 'departement_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('utilisateurs', 'departement_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
